### ISSUE TITLE
Display country name instead of ID

### ISSUE THREAD

**Issue by ItsJustPW** [kadegray/statamic-country-and-region-fieldtypes#1]
Is it possible to display the country name on frontend instead of the 2 letter country code?

**Comment by kadegray** [comment]
Please see the end of this subheading in the readme: [https://github.com/kadegray/statamic-country-and-region-fieldtypes#country-fieldtype](https://github.com/kadegray/statamic-country-and-region-fieldtypes#country-fieldtype)

You can render the Country name with: `{{ field_handle }}`

If you are seeing the country code instead it may be that your country fieldtype for the field handle no longer exists or has been renamed and the handle you are using is simply rendering the data that was previously saved on the entry.

**Comment by kadegray** [comment]
Closing since this question has already been answered.

**Comment by kadegray** [comment]
Closing since this question has already been answered.
