### ISSUE TITLE
Optional region possibly not supported

### ISSUE THREAD

**Issue by dsuelzle** [kadegray/statamic-country-and-region-fieldtypes#2]
I'd like the region field to be optional, but that appears to cause an error based on the RegionFieldType class augment method not handling a null parameter (ie. $value = null). I've tried null checking in my antlers template, but the null check itself seems to also cause this error. Is optional region field supported? Thanks.

**Comment by kadegray** [comment]
Hi @dsuelzle, thank you for reporting this bug. I apologize for the time you might have lost on this.

I have pushed fixes in 1.0.4, https://github.com/kadegray/statamic-country-and-region-fieldtypes/commit/391f10af2a40a891a401226f9a063c4eb217d97c, please run `composer update kadegray/statamic-country-and-region-fieldtypes`.

**Comment by dsuelzle** [comment]
That resolved the issue, thank you!
