### ISSUE TITLE
Wrong Regex

### ISSUE THREAD

**Issue by ruegler** [kadegray/statamic-country-and-region-fieldtypes#8]
https://github.com/kadegray/statamic-country-and-region-fieldtypes/blob/b3c867b58247e504441ac2cdb941c98b95684551/src/Fieldtypes/RegionInCountryFieldtype.php#L105

The regex pattern is incorrect. The region can also be just a number or a letter, see Austria (AT-1 - AT-9). This is why no text is displayed for each region from Austria.

Correct Pattern: `$iso31662Regex = '/^[A-Za-z0-9]{2}-[A-Za-z0-9]{1,3}$/';`

**Comment by kadegray** [comment]
@ruegler Thank you for creating this issue and identifying the issue.

I'll be able to look at this in the next few hours.

**Comment by kadegray** [comment]
@ruegler I have released the fix in 1.2.4. https://github.com/kadegray/statamic-country-and-region-fieldtypes/compare/1.2.2...1.2.4

Please run `composer update kadegray/statamic-country-and-region-fieldtypes`.

**Comment by ruegler** [comment]
@kadegray Thanks for the quick response and fix
